package com.clockpone.dynamicdao;

import com.clockbone.constant.Constant;
import com.clockbone.filter.DataSource;
import com.clockpone.domain.UserNew;

import java.util.List;

public interface UserNewMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Mar 23 16:18:17 CST 2016
     */
    @DataSource(Constant.DATA_SOURCE_MAIN)
    int deleteByPrimaryKey(Integer UserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Mar 23 16:18:17 CST 2016
     */
    @DataSource(Constant.DATA_SOURCE_MAIN)
    int insert(UserNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Mar 23 16:18:17 CST 2016
     */
    @DataSource(Constant.DATA_SOURCE_BACK)
    UserNew selectByPrimaryKey(Integer UserId);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Mar 23 16:18:17 CST 2016
     */
    @DataSource(Constant.DATA_SOURCE_MAIN)
    int updateByPrimaryKeySelective(UserNew record);



    @DataSource("dataSourceBack")
    List<UserNew> getAll();
}