package com.clockpone.domain;

import java.util.Date;

public class UserNew {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userId
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private Integer UserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userName
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userPassword
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userNickname
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String userNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userRealname
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String userrealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userAge
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private Integer userAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userSex
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userAddress
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userPhone
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userMail
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String userMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userQQ
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String userQQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.regTime
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lastLogintime
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private Date lastLogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.level
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.province
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bankName
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.branchBank
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String branchbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.subbranchBank
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String subbranchbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.openBankName
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String openbankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bankAccountName
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String bankaccountname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bankAccount
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String bankaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.accountType
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String accounttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pay
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String pay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mark
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.parentNumber
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    private String parentnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userId
     *
     * @return the value of user.userId
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public Integer getUserId() {
        return UserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userId
     *
     * @param UserId the value for user.userId
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setUserId(Integer UserId) {
        this.UserId = UserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userName
     *
     * @return the value of user.userName
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userName
     *
     * @param userName the value for user.userName
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userPassword
     *
     * @return the value of user.userPassword
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userPassword
     *
     * @param userPassword the value for user.userPassword
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userNickname
     *
     * @return the value of user.userNickname
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getUserNickName() {
        return userNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userNickname
     *
     * @param userNickName the value for user.userNickname
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setUserNickName(String userNickName) {
        this.userNickName = userNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userRealname
     *
     * @return the value of user.userRealname
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getUserrealname() {
        return userrealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userRealname
     *
     * @param userrealname the value for user.userRealname
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setUserrealname(String userrealname) {
        this.userrealname = userrealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userAge
     *
     * @return the value of user.userAge
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userAge
     *
     * @param userAge the value for user.userAge
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userSex
     *
     * @return the value of user.userSex
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userSex
     *
     * @param userSex the value for user.userSex
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userAddress
     *
     * @return the value of user.userAddress
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userAddress
     *
     * @param userAddress the value for user.userAddress
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userPhone
     *
     * @return the value of user.userPhone
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userPhone
     *
     * @param userPhone the value for user.userPhone
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userMail
     *
     * @return the value of user.userMail
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userMail
     *
     * @param userMail the value for user.userMail
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userQQ
     *
     * @return the value of user.userQQ
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getUserQQ() {
        return userQQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userQQ
     *
     * @param userQQ the value for user.userQQ
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setUserQQ(String userQQ) {
        this.userQQ = userQQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.regTime
     *
     * @return the value of user.regTime
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.regTime
     *
     * @param regTime the value for user.regTime
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lastLogintime
     *
     * @return the value of user.lastLogintime
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public Date getLastLogintime() {
        return lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lastLogintime
     *
     * @param lastLogintime the value for user.lastLogintime
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setLastLogintime(Date lastLogintime) {
        this.lastLogintime = lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.level
     *
     * @return the value of user.level
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.level
     *
     * @param level the value for user.level
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.province
     *
     * @return the value of user.province
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.province
     *
     * @param province the value for user.province
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city
     *
     * @return the value of user.city
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city
     *
     * @param city the value for user.city
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bankName
     *
     * @return the value of user.bankName
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bankName
     *
     * @param bankname the value for user.bankName
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.branchBank
     *
     * @return the value of user.branchBank
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getBranchbank() {
        return branchbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.branchBank
     *
     * @param branchbank the value for user.branchBank
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setBranchbank(String branchbank) {
        this.branchbank = branchbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.subbranchBank
     *
     * @return the value of user.subbranchBank
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getSubbranchbank() {
        return subbranchbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.subbranchBank
     *
     * @param subbranchbank the value for user.subbranchBank
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setSubbranchbank(String subbranchbank) {
        this.subbranchbank = subbranchbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.openBankName
     *
     * @return the value of user.openBankName
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getOpenbankname() {
        return openbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.openBankName
     *
     * @param openbankname the value for user.openBankName
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setOpenbankname(String openbankname) {
        this.openbankname = openbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bankAccountName
     *
     * @return the value of user.bankAccountName
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getBankaccountname() {
        return bankaccountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bankAccountName
     *
     * @param bankaccountname the value for user.bankAccountName
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setBankaccountname(String bankaccountname) {
        this.bankaccountname = bankaccountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bankAccount
     *
     * @return the value of user.bankAccount
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getBankaccount() {
        return bankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bankAccount
     *
     * @param bankaccount the value for user.bankAccount
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setBankaccount(String bankaccount) {
        this.bankaccount = bankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.accountType
     *
     * @return the value of user.accountType
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getAccounttype() {
        return accounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.accountType
     *
     * @param accounttype the value for user.accountType
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setAccounttype(String accounttype) {
        this.accounttype = accounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pay
     *
     * @return the value of user.pay
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pay
     *
     * @param pay the value for user.pay
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setPay(String pay) {
        this.pay = pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mark
     *
     * @return the value of user.mark
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mark
     *
     * @param mark the value for user.mark
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.parentNumber
     *
     * @return the value of user.parentNumber
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public String getParentnumber() {
        return parentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.parentNumber
     *
     * @param parentnumber the value for user.parentNumber
     *
     * @mbggenerated Wed Mar 23 16:40:12 CST 2016
     */
    public void setParentnumber(String parentnumber) {
        this.parentnumber = parentnumber;
    }


    @Override
    public String toString() {
        return "UserNew{" +
                "UserId=" + UserId +
                ", userName='" + userName + '\'' +
                ", userPassword='" + userPassword + '\'' +
                ", userNickName='" + userNickName + '\'' +
                ", userrealname='" + userrealname + '\'' +
                ", userAge=" + userAge +
                ", userSex='" + userSex + '\'' +
                ", userAddress='" + userAddress + '\'' +
                ", userPhone='" + userPhone + '\'' +
                ", userMail='" + userMail + '\'' +
                ", userQQ='" + userQQ + '\'' +
                ", regTime=" + regTime +
                ", lastLogintime=" + lastLogintime +
                ", level=" + level +
                ", province='" + province + '\'' +
                ", city='" + city + '\'' +
                ", bankname='" + bankname + '\'' +
                ", branchbank='" + branchbank + '\'' +
                ", subbranchbank='" + subbranchbank + '\'' +
                ", openbankname='" + openbankname + '\'' +
                ", bankaccountname='" + bankaccountname + '\'' +
                ", bankaccount='" + bankaccount + '\'' +
                ", accounttype='" + accounttype + '\'' +
                ", pay='" + pay + '\'' +
                ", mark='" + mark + '\'' +
                ", status='" + status + '\'' +
                ", parentnumber='" + parentnumber + '\'' +
                '}';
    }
}